//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class BookEntities : DbContext
    {
        public BookEntities()
            : base("name=BookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors { get; set; }
        public DbSet<Book> Books { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spGetAuthor_Result> spGetAuthor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAuthor_Result>("spGetAuthor");
        }
    
        public virtual ObjectResult<spGetBooks_Result> spGetBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBooks_Result>("spGetBooks");
        }
    
        public virtual ObjectResult<spGetCategory_Result> spGetCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCategory_Result>("spGetCategory");
        }
    }
}
